# Generated by Django 4.2.3 on 2023-08-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proserve_app', '0004_remove_userprofile_experiance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
    ]
