# Generated by Django 4.2.3 on 2023-08-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proserve_app', '0005_remove_userprofile_gender_workerprofile_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='profile',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='gender',
        ),
    ]
