# Generated by Django 4.2.3 on 2023-08-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proserve_app', '0006_rename_profile_workerprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='user',
            new_name='profile',
        ),
    ]
