# Generated by Django 4.2.3 on 2023-08-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proserve_app', '0002_workerprofile_clientprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='price',
        ),
    ]
