# Generated by Django 4.2.3 on 2023-08-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proserve_app', '0007_rename_user_workerprofile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Address',
        ),
    ]
