# Generated by Django 4.2.3 on 2023-08-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proserve_app', '0008_remove_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
