# Generated by Django 4.2.3 on 2023-08-26 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proserve_app', '0009_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proserve_app.userprofile'),
        ),
    ]
